# Generated by Django 2.2.1 on 2019-05-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='body',
            new_name='donkey_content',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='pub_date',
            new_name='donkey_time',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title',
        ),
        migrations.AddField(
            model_name='blog',
            name='donkey_hits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='donkey_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='donkey_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
